replicaCount: 1

image:
  repository: rg.fr-par.scw.cloud/sovereign-cloud-wisdom/sovereign-cloud-wisdom
  tag: latest
  pullSecret: sovereign-cloud-wisdom-registry

database:
  configMap: wisdom-db-config
  secret: wisdom-db-credentials

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 256Mi

cloudProvider: scaleway
