replicaCount: 1

image:
  repository: ""
  tag: latest
  pullSecret: ""

database:
  configMap: wisdom-db-config
  secret: wisdom-db-credentials

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 256Mi

cloudProvider: ""
