apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.database.clusterName }}
spec:
  instances: {{ .Values.database.instances }}
  storage:
    size: {{ .Values.database.storage }}
  resources:
    requests:
      memory: {{ .Values.database.resources.requests.memory }}
  postgresql:
    parameters:
      shared_buffers: "64MB"
      effective_cache_size: "128MB"
  bootstrap:
    initdb:
      database: app
      owner: app_admin
