apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.image.pullSecret }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: scaleway-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.image.pullSecret }}
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ "{{" }} .credentials {{ "}}" }}'
  data:
    - secretKey: credentials
      remoteRef:
        key: name:wisdom-registry-credentials
